#! /bin/bash

echo "========= Begin starting up emoscapeDataCollector ========="

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
$DIR/emoscapeDataCollector-2

$DIR/checker &
/Applications/muse/muse-io --osc osc.udp://localhost:8000

echo "========= Finished starting up emoscapeDataCollector ========="
