#! /bin/bash

export PATH="$PATH:/Applications/Muse"
export DYLD_FALLBACK_LIBRARY_PATH="$DYLD_FALLBACK_LIBRARY_PATH:/Applications/Muse"

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$DIR/checker &
muse-io --osc osc.udp://localhost:8000

$DIR/emoscapeDataCollector-2
